#!/bin/env bash

set -e

[ -z $1 ] && echo "Usage: $0 url [parts]" && exit 1

my_get(){
    local f=$(echo $1 | rev | cut -d'/' -f 1 | rev)
    [ -f $f ] || {
        wget --spider -q $1 || exit 0
        wget -qO $f $1
        echo $f ... Done
    }
}

my_get $1

for i in $( eval echo {1..${2:-100}} ); do
    my_get $1.$i || exit 0
done

exit 0
